version: '3.8'

services:
  # Головной офис
  main_office:
    image: postgres:15
    container_name: main_office_db
    environment:
      POSTGRES_USER: main_office_user
      POSTGRES_PASSWORD: main_office_password
      POSTGRES_DB: main_office_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/main_office:/var/lib/postgresql/data
    networks:
      - db_network

  # Филиал 1
  branch_1:
    image: postgres:15
    container_name: branch_1_db
    environment:
      POSTGRES_USER: branch_1_user
      POSTGRES_PASSWORD: branch_1_password
      POSTGRES_DB: branch_1_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/branch_1:/var/lib/postgresql/data
    networks:
      - db_network
    depends_on:
      - main_office

  # Филиал 2
  branch_2:
    image: postgres:15
    container_name: branch_2_db
    environment:
      POSTGRES_USER: branch_2_user
      POSTGRES_PASSWORD: branch_2_password
      POSTGRES_DB: branch_2_db
    ports:
      - "5434:5432"
    volumes:
      - ./data/branch_2:/var/lib/postgresql/data
    networks:
      - db_network
    depends_on:
      - main_office

  # Филиал 3
  branch_3:
    image: postgres:15
    container_name: branch_3_db
    environment:
      POSTGRES_USER: branch_3_user
      POSTGRES_PASSWORD: branch_3_password
      POSTGRES_DB: branch_3_db
    ports:
      - "5435:5432"
    volumes:
      - ./data/branch_3:/var/lib/postgresql/data
    networks:
      - db_network
    depends_on:
      - main_office

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: tpk@mail.ru
      PGADMIN_DEFAULT_PASSWORD: default
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_network
    depends_on:
      - main_office
      - branch_1
      - branch_2
      - branch_3

volumes:
  pgadmin_data:
    driver: local

networks:
  db_network:
    driver: bridge
